### ISSUE TITLE
Workspace switching shows wallpaper

### ISSUE THREAD

**Issue by Odeni** [allusive-dev/picom-allusive#28]
When switching workspaces, wallpaper flashes briefly when fading/animations are enabled. Could the wallpaper be ignored or replaced with just #000? If wallpaper is not set, it looks fine. 

Using i3wm.

**Comment by allusive-dev** [comment]
@Odeni 
Can you please attach a video this happening as I am not sure what you mean.

**Comment by Odeni** [comment]
Old problem. Video can be seen here:
https://github.com/yshui/picom/issues/16#issuecomment-431603866

**Comment by allusive-dev** [comment]
Hm. This is kind of difficult because that is how it is meant to work. When you switch to a new workspace the current windows fade/animate out and the new windows fade/animate in, so whatever is behind them is briefly visible.
The only way to fix that is to disable fading.
Like you said though making it transparent would break how animations are supposed to come in when opened/become visible when switching between workspaces.

**Comment by allusive-dev** [comment]
@Odeni 
It looks like somebody solved the issue by using these configuration options.

```
fading = true
fade-in-step = 1
fade-out-step = 1
fade-delta = 50
```

**Comment by Odeni** [comment]
This basically disables fading. My solution so far was to not use a wallpaper.

**Comment by allusive-dev** [comment]
@Odeni 
I'm a bit confused then because, what you are describing to me is the purpose of fading, but you don't want to disable it?
I don't think there is a way to "fix" this besides disabling fading. There is not a lot I can really do to picom to change what is happening at this stage unfortunately. I'm quite sorry about it.

**Comment by allusive-dev** [comment]
@Odeni 
You could try using this option.

```
no-fading-openclose = true;
```

**Comment by Odeni** [comment]
It should be fading from what is showing on one workspace to what is showing on second. If I can't see the wallpaper on either workspace, picom should not show it. It's probably impossible to fix or someone would have done it already.

**Comment by allusive-dev** [comment]
> It's probably impossible to fix or someone would have done it already.

I think you might be right, I understand what you mean now about fading between windows instead of fading out then in but personally I would not know how to do that. (Also it would break animations since they would collide).

**Comment by Odeni** [comment]
Alright, thanks for looking into it.

**Comment by allusive-dev** [comment]
No problem. I am sorry I couldn't be more helpful.
